### ISSUE TITLE
Better workspace/crates handling

### ISSUE THREAD

**Issue by pepperoni21** [pepperoni21/ollama-rs#110]
Hey, just published version 0.2.3 that introduces a macro crate for handling custom user-defined functions.

I'm not really used to publishing workspaces to crates.io. I just published both `ollama-rs` and `ollama-rs-macros` crates separately, and it requires `ollama-rs` to use the published version of `ollama-rs-macros` on crates.io so I specified the current version of the macro crate inside the `Cargo.toml` of `ollama-rs`:
```toml
ollama-rs-macros = { version = "0.2.3", optional = true }
```
While on the master branch it uses the workspace dependency. I don't know if there's a better way to handle that. Probably. Hopefully it doesn't break anything, and the master branch remains accessible for use as a dependency.

**Comment by cyrilleberger** [comment]
You could use https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table to inherits property, including version. Something like:

/ollama-rs/Cargo.toml

```toml
[package]
version.workspace = true

[dependencies]
ollama-rs-macros = { workspace = true, optional = true }
```


/ollama-rs-macros/Cargo.toml

```toml
[package]
version.workspace = true
```


/Cargo.toml

```toml
[workspace.package]
version = "0.2.3"

[workspace.dependencies]
ollama-rs-macros = { version = "0.2.3", path = "ollama-rs-macros" }
```
