### ISSUE TITLE
module info, modelfile lists everything

### ISSUE THREAD

**Issue by picobyte** [pepperoni21/ollama-rs#137]
querying module info, modelfile does not just return the modelfile, but rather everything.

```rust
use ollama_rs::Ollama;

#[tokio::main]
async fn main() {
    let ollama = Ollama::new("http://localhost".to_string(), 11434);
    let res = ollama
        .show_model_info("llama3.2:latest".to_string())
        .await
        .unwrap();
    // println!("'{}'", res.license); // Ok
    // println!("'{}'", res.parameters); // Ok
    // println!("'{}'", res.template); // Ok
    println!("'{}'", res.modelfile); // lists everything
}
```

```toml
[package]
name = "bla"
version = "0.1.0"
edition = "2021"

[dependencies]
ollama-rs = "0.2.5"
tokio = { version = "1.43.0", features = ["full"] }
```
